name: course_schedule
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.17.0


dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  flutter:
    sdk: flutter
  lints: ^2.0.0
  wheel_chooser: ^1.1.2

